### ISSUE TITLE
Missing GTMOAuth2ViewTouch.nib when built at framework

### ISSUE THREAD

**Issue by erickoledadevrel** [google/gtm-oauth2#63]
When building the project as a framework, for instance by include `use_frameworks!` in the Podfile, using the library will result in a black screen and an error like:

    MyApp[123:456]: missing GTMOAuth2ViewTouch.nib

The root of the problem seems to be that the code is looking for the nib/xib in the main bundle, which isn't correctly when the library is included as a framework. As per the [Cocoapods documentation on frameworks](http://blog.cocoapods.org/CocoaPods-0.36/#caveats), the library should use `NSBundle bundleForClass` instead of `NSBundle mainBundle` when looking for the resources, to ensure it works correctly whether built as a static library or a framework.

**Comment by perotinus** [comment]
@erickoledadevrel Appreciate the PR! Do you think you'll be able to sign the CLA?

**Comment by erickoledadevrel** [comment]
I work at Google, so I didn't think it was required.

**Comment by erickoledadevrel** [comment]
I fixed my email address on the commit, so CLABot is happy :-)

**Comment by weibel** [comment]
We're still seeing this on 1.1.4 after migrating to use_frameworks! on CocoaPods.

**Comment by weibel** [comment]
The problem was that we had subclassed `GTMOAuth2ViewControllerTouch`. In that case `[NSBundle bundleForClass:[self class]]` will give you the main bundle.

Inserting the following in the child class solved the problem, but there might be a more elegant solution. 

```
+ (NSBundle *)authNibBundle {
   // subclasses may override this to specify a custom nib bundle
   return [NSBundle bundleForClass:[GTMOAuth2ViewControllerTouch class]];
}
```
